name: Build Linux
on:
  release:
    types: [published]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.1
        with:
          build-name: SimpleWorship Display linux/amd64
          build-platform: linux/amd64
          nsis: false
