name: Wails build
on:
  release:
    types: [published]
jobs:
  build:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: simpleworship-display-linux.amd64, platform: linux/amd64, os: ubuntu-latest},
          {name: simpleworship-display-window-64bit, platform: windows/amd64, os: windows-latest},
          {name: simpleworship-display-osx, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2-
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.1
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
